In [5]:
# Import NumPy
import numpy as np

In [6]:
# Basics of array building and broadcasting
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
[0, 1, 2, 3,4 ]

[0, 1, 2, 3, 4]

In [8]:
a = np.arange(5)

In [9]:
a * 2

array([0, 2, 4, 6, 8])

In [10]:
a + 2

array([2, 3, 4, 5, 6])

In [11]:
a + a

array([0, 2, 4, 6, 8])

In [12]:
# NumPy array attributes
a.shape

(5,)

In [13]:
mat = np.arange(4)

In [14]:
mat

array([0, 1, 2, 3])

In [15]:
# Reshaping
mat.reshape(2, 2)

array([[0, 1],
       [2, 3]])

In [16]:
mat = mat.reshape(2, 2)

In [17]:
mat

array([[0, 1],
       [2, 3]])

In [18]:
np.sum(mat)

6

In [19]:
# Summations over axes
np.sum(mat, axis=1)

array([1, 5])

In [20]:
np.sum(mat, axis=0)

array([2, 4])

In [21]:
# build a matrix that is 2x3
mat2 = np.arange(6).reshape(2, 3)

In [22]:
mat2

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
mat2.shape

(2, 3)

In [24]:
# Shape based broadcasting
vec3 = np.arange(3)

In [25]:
print(mat2.shape)
print(vec3.shape)

(2, 3)
(3,)


In [26]:
vec3 * mat2

array([[ 0,  1,  4],
       [ 0,  4, 10]])

In [27]:
vec2 = np.arange(2)

In [28]:
print(mat2.shape)
print(vec2.shape)

(2, 3)
(2,)


In [29]:
# Broadcasting errors
mat2 * vec2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [30]:
# Transpose of a vector is a vector
vec2.T

array([0, 1])

In [31]:
vec2.reshape(2, 1)

array([[0],
       [1]])

In [32]:
vec2.reshape(2, 1) * mat2

array([[0, 0, 0],
       [3, 4, 5]])

In [33]:
A = np.arange(6).reshape(2, 3)
B = np.arange(6).reshape(3, 2)

In [34]:
# \sum_j A_ij B_jk -> C_ik
np.dot(A, B)

array([[10, 13],
       [28, 40]])

In [35]:
# Challenge problem, matrix multiplication 
# A_ij B_jk -> C_ijk -> C_ik
# A_(i, j, 1)
# B_(1, j, k)
# -> C_(i, j, k)
# Sum over axis j
np.sum(A.reshape(A.shape + (1, )) * B, axis=1)

array([[10, 13],
       [28, 40]])

In [36]:
# Timings of the various approaches
A_big = np.random.rand(200, 400)
B_big = np.random.rand(400, 200)

In [37]:
%timeit np.sum(A.reshape(A.shape + (1, )) * B, axis=1)

The slowest run took 6.69 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.75 µs per loop


In [38]:
%timeit np.sum(A_big.reshape(A_big.shape + (1, )) * B_big, axis=1)

10 loops, best of 3: 63.8 ms per loop


In [39]:
%timeit np.dot(A_big, B_big)

The slowest run took 197.55 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 221 µs per loop


In [40]:
# A_ij B_jk -> C_ik
np.einsum("ij,jk->ik", A, B)

array([[10, 13],
       [28, 40]])

In [41]:
%timeit np.einsum("ij,jk->ik", A_big, B_big)

100 loops, best of 3: 5.14 ms per loop


In [42]:
# Slicing tutorial
A

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
A[0]

array([0, 1, 2])

In [44]:
nd = np.random.rand(2, 3, 2)

In [45]:
nd[0]

array([[ 0.23831456,  0.26886795],
       [ 0.07475848,  0.00158496],
       [ 0.9753937 ,  0.05751102]])

In [46]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
A[:, 0]

array([0, 3])

In [48]:
nd.shape

(2, 3, 2)

In [49]:
nd[:, :, 0]

array([[ 0.23831456,  0.07475848,  0.9753937 ],
       [ 0.96307633,  0.81317975,  0.15727507]])

In [50]:
nd[..., 0]

array([[ 0.23831456,  0.07475848,  0.9753937 ],
       [ 0.96307633,  0.81317975,  0.15727507]])

In [51]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
A[:, :2]

array([[0, 1],
       [3, 4]])

In [53]:
A[:, 1:]

array([[1, 2],
       [4, 5]])

In [54]:
C = np.arange(12).reshape(4, 3)
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
C[1:3, 1]

array([4, 7])

In [56]:
C[1:3, 1:2]

array([[4],
       [7]])

In [57]:
view = C[1:3, 1]

In [58]:
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
# A view is a part of the larger data, we modify in place
view *= 2

In [60]:
view

array([ 8, 14])

In [61]:
C

array([[ 0,  1,  2],
       [ 3,  8,  5],
       [ 6, 14,  8],
       [ 9, 10, 11]])

In [62]:
# We can however, copy the data
data = C[1:3, 1].copy()

In [63]:
data

array([ 8, 14])

In [64]:
data *= 2
print(data)

[16 28]


In [65]:
C

array([[ 0,  1,  2],
       [ 3,  8,  5],
       [ 6, 14,  8],
       [ 9, 10, 11]])

In [66]:
# Challenge, write a function that properly checks for failures
def broadcasting_dot(A, B):
    # A_ij B_jk -> C_ik
    
    shape_A = A.shape
    shape_B = B.shape
            
    # Dimensions of each array must be 2
    if (len(shape_A) != 2) or (len(shape_B) != 2):
        raise Exception("Input arrays must be of ndim=2")
        
    # If columns of A and rows of B do not match
    if (shape_A[1] != shape_B[0]):
        raise Exception("Columns of A and rows of B do not match!")

    # Memory constraints(i * j * k) must be less than ~1e7
    if (shape_A[0] * shape_A[1] * shape_B[1]) > 1e7:
        raise Exception("Intermediate array is too large!")
    
    A = A.reshape(A.shape + (1, ))
    tmp = A * B
    return np.sum(tmp, axis=1)

In [67]:
D = np.random.rand(5, 5)
broadcasting_dot(np.random.rand(1000, 1000), np.random.rand(1000, 1000))

Exception: Intermediate array is too large!